<a href="https://colab.research.google.com/github/phelippe-marques/projeto-final-poo/blob/main/Projeto_TDS_DSW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dfrenuncias = pd.read_csv('/content/renuncias.CSV', sep=';')

print("1) Base de dados completa:")
display(dfrenuncias)
print('\n\n')

print("2) Tamanho do dataframe:")
print('Quantidade de linhas e colunas, respectivamente:', dfrenuncias.shape)
print('\n\n')

print("3) Características da linha {x}:")
print(dfrenuncias.loc[80])
print('\n\n')

print("4) Verificação se o dataframe está vazio:")
if dfrenuncias.empty:
  print('O dataframe está vazio')
else:
  print('O dataframe não está vazio')
print('\n\n')

print("5) Primeiros 5 registros:")
print(dfrenuncias.head(5))
print('\n\n')

print("6) Inclusão de linha:")
novo_registro = ['PA', 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 2020]
dfrenuncias.loc[len(dfrenuncias)] = novo_registro
display(dfrenuncias)
print('\n\n')

print("7) Exclusão de linha:")
dfrenuncias.drop(81, inplace=True)
display(dfrenuncias)
print('\n\n')

print("8) Transposição da coluna para a linha:")
dfrenuncias_transposto = dfrenuncias.T.copy()
display(dfrenuncias_transposto)
print('\n\n')

print("9) 1ª e 2ª coluna:")
display(dfrenuncias.iloc[:, 0:2])
print('\n\n')

print("10) Desenvolvimento do Projeto:")
print("Informe aqui como o projeto foi desenvolvido.")
print('\n\n')

print('-----------------------------------------------------------------------------------------------')
'''dfrenuncias['Despesas_Medicas'] = pd.to_numeric(dfrenuncias['Despesas_Medicas'], errors = 'coerce')
dfrenuncias['Despesas_Instrucao'] = pd.to_numeric(dfrenuncias['Despesas_Instrucao'], errors = 'coerce')
dfrenuncias['Contrato_Trabalho'] = pd.to_numeric(dfrenuncias['Contrato_Trabalho'], errors = 'coerce')
dfrenuncias['Aposentadoria'] = pd.to_numeric(dfrenuncias['Aposentadoria'], errors = 'coerce')
dfrenuncias['Pensao'] = pd.to_numeric(dfrenuncias['Pensao'], errors = 'coerce')
dfrenuncias['Seguro'] = pd.to_numeric(dfrenuncias['Seguro'], errors = 'coerce')

dfrenuncias['Despesas_Medicas'] = dfrenuncias['Despesas_Medicas'].astype(float)
dfrenuncias['Despesas_Instrucao'] = dfrenuncias['Despesas_Instrucao'].astype(float)
dfrenuncias['Contrato_Trabalho'] = dfrenuncias['Contrato_Trabalho'].astype(float)
dfrenuncias['Aposentadoria'] = dfrenuncias['Aposentadoria'].astype(float)
dfrenuncias['Pensao'] = dfrenuncias['Pensao'].astype(float)
dfrenuncias['Seguro'] = dfrenuncias['Seguro'].astype(float)

print(dfrenuncias.dtypes)

dfrenuncias['Total'] = dfrenuncias.apply(lambda row: row['Despesas_Medicas':'Seguro'].sum(), axis=1)
display(dfrenuncias)

dfrenuncias['Total'] = dfrenuncias['Despesas_Medicas'] + dfrenuncias['Despesas_Instrucao'] + dfrenuncias['Contrato_Trabalho'] + dfrenuncias['Aposentadoria'] + dfrenuncias['Pensao'] + dfrenuncias['Seguro']
display(dfrenuncias)

n = 'Norte'
s = 'Sul'
se = 'Sudeste'
co = 'Centro-Oeste'
ne = 'Nordeste'
if(dfrenuncias['UF'] == ('AC', 'AM', 'PA', 'RO','RR')):
  regiao = n
elif(dfrenuncias['UF'] == ('DF','GO','MT','MS')):
  regiao = co
elif(dfrenuncias['UF'] == ('BA', 'CE', 'MA', 'PB', 'PE', 'PI', 'RN', 'SE')):
  regiao = ne
elif(dfrenuncias['UF'] == ('ES','MG', 'RJ', 'SP')):
  regiao = se
elif(dfrenuncias['UF'] == ('PR', 'RS', 'SC')):
  regiao = s

dfrenuncias['Regiao'] = regiao

display(dfrenuncias)'''

1) Base de dados completa:

,UF,Despesas_Medicas,Despesas_Instrucao,Contrato_Trabalho,Aposentadoria,Pensao,Seguro,Ano
0,AC,"54.566.623,96","15.356.356,47","6.605.814,80","24.937.576,02","40.702.012,72","792.667,82",2022
1,RO,"141.244.976,54","24.179.749,56","17.273.350,62","43.683.985,19","101.447.708,58","3.810.312,05",2022
2,RR,"41.320.955,62","9.844.803,99","5.289.044,40","15.938.780,74","21.069.928,53","343.385,73",2022
3,AM,"194.062.016,81","75.704.143,17","44.675.540,23","94.088.086,41","142.525.951,31","8.038.584,33",2022
4,PA,"489.110.814,55","158.797.843,73","60.339.514,90","220.130.257,17","265.768.640,17","15.048.418,00",2022
...,...,...,...,...,...,...,...,...
76,RS,"1.046.923.198,81","204.233.880,30","478.229.193,17","863.609.885,69","1.262.691.676,00","104.689.213,32",2020
77,MS,"247.537.087,15","50.107.587,21","48.151.156,72","117.561.127,33","202.112.451,00","14.043.521,05",2020
78,MT,"322.068.998,78","68.248.291,75","63.500.118,78","97.851.441,43","172.458.715,00","12.801.944,71",2020
79,GO,"581.606.318,26","130.483.482,33","131.341.739,42","244.224.259,81","435.264.510,00","28.720.357,84",2020
80,DF,"1.047.778.364,74","169.542.790,13","225.224.710,31","363.513.742,32","1.126.225.741,00","41.577.226,78",2020

2) Tamanho do dataframe:
Quantidade de linhas e colunas, respectivamente: (81, 8)



3) Características da linha {x}:
UF                                    DF
Despesas_Medicas       1.047.778.364,74
Despesas_Instrucao       169.542.790,13
Contrato_Trabalho        225.224.710,31
Aposentadoria            363.513.742,32
Pensao                 1.126.225.741,00
Seguro                    41.577.226,78
Ano                                 2020
Name: 80, dtype: object



4) Verificação se o dataframe está vazio:
O dataframe não está vazio



5) Primeiros 5 registros:
   UF  Despesas_Medicas Despesas_Instrucao Contrato_Trabalho  \
0  AC    54.566.623,96      15.356.356,47      6.605.814,80
1  RO   141.244.976,54      24.179.749,56     17.273.350,62
2  RR    41.320.955,62       9.844.803,99      5.289.044,40
3  AM   194.062.016,81      75.704.143,17     44.675.540,23
4  PA   489.110.814,55     158.797.843,73     60.339.514,90

      Aposentadoria            Pensao           Seguro   Ano
0    24.937.576,02     40.702.012,72       792.667,82   2022
1    43.683.985,19    101.447.708,58     3.810.312,05   2022
2    15.938.780,74     21.069.928,53       343.385,73   2022
3    94.088.086,41    142.525.951,31     8.038.584,33   2022
4   220.130.257,17    265.768.640,17    15.048.418,00   2022



6) Inclusão de linha:

,UF,Despesas_Medicas,Despesas_Instrucao,Contrato_Trabalho,Aposentadoria,Pensao,Seguro,Ano
0,AC,"54.566.623,96","15.356.356,47","6.605.814,80","24.937.576,02","40.702.012,72","792.667,82",2022
1,RO,"141.244.976,54","24.179.749,56","17.273.350,62","43.683.985,19","101.447.708,58","3.810.312,05",2022
2,RR,"41.320.955,62","9.844.803,99","5.289.044,40","15.938.780,74","21.069.928,53","343.385,73",2022
3,AM,"194.062.016,81","75.704.143,17","44.675.540,23","94.088.086,41","142.525.951,31","8.038.584,33",2022
4,PA,"489.110.814,55","158.797.843,73","60.339.514,90","220.130.257,17","265.768.640,17","15.048.418,00",2022
...,...,...,...,...,...,...,...,...
77,MS,"247.537.087,15","50.107.587,21","48.151.156,72","117.561.127,33","202.112.451,00","14.043.521,05",2020
78,MT,"322.068.998,78","68.248.291,75","63.500.118,78","97.851.441,43","172.458.715,00","12.801.944,71",2020
79,GO,"581.606.318,26","130.483.482,33","131.341.739,42","244.224.259,81","435.264.510,00","28.720.357,84",2020
80,DF,"1.047.778.364,74","169.542.790,13","225.224.710,31","363.513.742,32","1.126.225.741,00","41.577.226,78",2020
81,PA,0.0,0.0,0.0,0.0,0.0,0.0,2020

7) Exclusão de linha:

,UF,Despesas_Medicas,Despesas_Instrucao,Contrato_Trabalho,Aposentadoria,Pensao,Seguro,Ano
0,AC,"54.566.623,96","15.356.356,47","6.605.814,80","24.937.576,02","40.702.012,72","792.667,82",2022
1,RO,"141.244.976,54","24.179.749,56","17.273.350,62","43.683.985,19","101.447.708,58","3.810.312,05",2022
2,RR,"41.320.955,62","9.844.803,99","5.289.044,40","15.938.780,74","21.069.928,53","343.385,73",2022
3,AM,"194.062.016,81","75.704.143,17","44.675.540,23","94.088.086,41","142.525.951,31","8.038.584,33",2022
4,PA,"489.110.814,55","158.797.843,73","60.339.514,90","220.130.257,17","265.768.640,17","15.048.418,00",2022
...,...,...,...,...,...,...,...,...
76,RS,"1.046.923.198,81","204.233.880,30","478.229.193,17","863.609.885,69","1.262.691.676,00","104.689.213,32",2020
77,MS,"247.537.087,15","50.107.587,21","48.151.156,72","117.561.127,33","202.112.451,00","14.043.521,05",2020
78,MT,"322.068.998,78","68.248.291,75","63.500.118,78","97.851.441,43","172.458.715,00","12.801.944,71",2020
79,GO,"581.606.318,26","130.483.482,33","131.341.739,42","244.224.259,81","435.264.510,00","28.720.357,84",2020
80,DF,"1.047.778.364,74","169.542.790,13","225.224.710,31","363.513.742,32","1.126.225.741,00","41.577.226,78",2020

8) Transposição da coluna para a linha:

,0,1,2,3,4,5,6,7,8,9,...,71,72,73,74,75,76,77,78,79,80
UF,AC,RO,RR,AM,PA,AP,TO,MA,PI,CE,...,MG,RJ,SP,PR,SC,RS,MS,MT,GO,DF
Despesas_Medicas,"54.566.623,96","141.244.976,54","41.320.955,62","194.062.016,81","489.110.814,55","82.308.988,96","117.884.895,17","283.162.739,62","183.714.477,14","564.664.393,35",...,"1.278.500.209,96","2.533.284.101,00","5.103.856.848,07","819.247.906,81","542.817.098,39","1.046.923.198,81","247.537.087,15","322.068.998,78","581.606.318,26","1.047.778.364,74"
Despesas_Instrucao,"15.356.356,47","24.179.749,56","9.844.803,99","75.704.143,17","158.797.843,73","32.344.616,88","27.222.935,20","90.801.400,74","44.883.261,64","127.727.122,25",...,"298.171.953,64","392.064.358,36","987.762.019,43","180.985.622,56","118.657.799,39","204.233.880,30","50.107.587,21","68.248.291,75","130.483.482,33","169.542.790,13"
Contrato_Trabalho,"6.605.814,80","17.273.350,62","5.289.044,40","44.675.540,23","60.339.514,90","6.631.221,95","22.327.623,54","31.206.543,54","17.095.749,51","90.772.039,17",...,"544.725.703,37","918.629.153,89","3.046.798.185,54","473.684.586,25","301.642.265,06","478.229.193,17","48.151.156,72","63.500.118,78","131.341.739,42","225.224.710,31"
Aposentadoria,"24.937.576,02","43.683.985,19","15.938.780,74","94.088.086,41","220.130.257,17","19.064.306,59","32.715.399,35","123.926.384,44","101.250.314,06","283.529.981,59",...,"1.004.249.616,21","1.704.852.737,49","2.890.888.333,17","576.301.655,15","388.862.638,45","863.609.885,69","117.561.127,33","97.851.441,43","244.224.259,81","363.513.742,32"
Pensao,"40.702.012,72","101.447.708,58","21.069.928,53","142.525.951,31","265.768.640,17","20.514.328,34","53.984.201,23","148.765.222,31","156.887.480,31","521.232.530,81",...,"1.666.715.458,00","2.928.124.275,00","3.156.009.526,00","751.178.679,00","742.820.692,00","1.262.691.676,00","202.112.451,00","172.458.715,00","435.264.510,00","1.126.225.741,00"
Seguro,"792.667,82","3.810.312,05","343.385,73","8.038.584,33","15.048.418,00","313.854,45","2.160.897,61","11.571.493,54","4.751.347,02","31.926.615,87",...,"86.056.473,94","214.568.971,11","617.021.176,16","78.383.445,79","61.958.113,96","104.689.213,32","14.043.521,05","12.801.944,71","28.720.357,84","41.577.226,78"
Ano,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,...,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020

9) 1ª e 2ª coluna:

    UF    Despesas_Medicas
0   AC      54.566.623,96
1   RO     141.244.976,54
2   RR      41.320.955,62
3   AM     194.062.016,81
4   PA     489.110.814,55
..  ..                 ...
76  RS   1.046.923.198,81
77  MS     247.537.087,15
78  MT     322.068.998,78
79  GO     581.606.318,26
80  DF   1.047.778.364,74

[81 rows x 2 columns]

10) Desenvolvimento do Projeto:
Informe aqui como o projeto foi desenvolvido.



-----------------------------------------------------------------------------------------------

"dfrenuncias['Despesas_Medicas'] = pd.to_numeric(dfrenuncias['Despesas_Medicas'], errors = 'coerce')\ndfrenuncias['Despesas_Instrucao'] = pd.to_numeric(dfrenuncias['Despesas_Instrucao'], errors = 'coerce')\ndfrenuncias['Contrato_Trabalho'] = pd.to_numeric(dfrenuncias['Contrato_Trabalho'], errors = 'coerce')\ndfrenuncias['Aposentadoria'] = pd.to_numeric(dfrenuncias['Aposentadoria'], errors = 'coerce')\ndfrenuncias['Pensao'] = pd.to_numeric(dfrenuncias['Pensao'], errors = 'coerce')\ndfrenuncias['Seguro'] = pd.to_numeric(dfrenuncias['Seguro'], errors = 'coerce')\n\ndfrenuncias['Despesas_Medicas'] = dfrenuncias['Despesas_Medicas'].astype(float)\ndfrenuncias['Despesas_Instrucao'] = dfrenuncias['Despesas_Instrucao'].astype(float)\ndfrenuncias['Contrato_Trabalho'] = dfrenuncias['Contrato_Trabalho'].astype(float)\ndfrenuncias['Aposentadoria'] = dfrenuncias['Aposentadoria'].astype(float)\ndfrenuncias['Pensao'] = dfrenuncias['Pensao'].astype(float)\ndfrenuncias['Seguro'] = dfrenuncias['Seguro'].astype(float)\n\nprint(dfrenuncias.dtypes)\n\ndfrenuncias['Total'] = dfrenuncias.apply(lambda row: row['Despesas_Medicas':'Seguro'].sum(), axis=1)\ndisplay(dfrenuncias)\n\ndfrenuncias['Total'] = dfrenuncias['Despesas_Medicas'] + dfrenuncias['Despesas_Instrucao'] + dfrenuncias['Contrato_Trabalho'] + dfrenuncias['Aposentadoria'] + dfrenuncias['Pensao'] + dfrenuncias['Seguro']\ndisplay(dfrenuncias)\n\nn = 'Norte'\ns = 'Sul'\nse = 'Sudeste'\nco = 'Centro-Oeste'\nne = 'Nordeste'\nif(dfrenuncias['UF'] == ('AC', 'AM', 'PA', 'RO','RR')):\n  regiao = n\nelif(dfrenuncias['UF'] == ('DF','GO','MT','MS')):\n  regiao = co\nelif(dfrenuncias['UF'] == ('BA', 'CE', 'MA', 'PB', 'PE', 'PI', 'RN', 'SE')):\n  regiao = ne\nelif(dfrenuncias['UF'] == ('ES','MG', 'RJ', 'SP')):\n  regiao = se\nelif(dfrenuncias['UF'] == ('PR', 'RS', 'SC')):\n  regiao = s\n\ndfrenuncias['Regiao'] = regiao\n\ndisplay(dfrenuncias)"